# uncomment for docker executor
#image: alpine:3.7

#stages:
#  - sync-upstream

# uncomment for docker executor and add private id_rsa corresponding with 
# public rsa deploy key as value to $PRIVATE_KEY
#before_script:
#  - apk -U add git openssh-client
#  - mkdir -p ~/.ssh/
# - echo -e "$SSH_PRIVATE" > ~/.ssh/id_rsa
#  - chmod 600 ~/.ssh/id_rsa
#  - eval `ssh-agent -s`
#  - ssh-add ~/.ssh/id_rsa
#  - ssh-keyscan -p8022 gitlab.bitsling.eu >> ~/.ssh/known_hosts

sync-upstream:
  stage: test
  tags: 
        - gem-rtsw
  script:
    # - git clone ssh://git@${CI_SERVER_HOST}:8022/${CI_PROJECT_PATH}  git_tmp
    # - cd git_tmp
    - git config user.email "$GITLAB_USER_EMAIL"
    - git config user.name "$GITLAB_USER_NAME"
    - git remote set-url origin ssh://git@${CI_SERVER_HOST}/${CI_PROJECT_PATH}
    # Delete all local branches but master
    - git checkout master; git branch | grep -v '^*' | xargs git branch -D || echo "no local branches but master, so not deleting"
    - git remote add upstream $UPSTREAM || echo "remote upstream already exists, continueing"
    - git fetch upstream
    - >
      for branch in $SYNC_BRANCHES; do
        echo "syncing branch $branch..."
        # look if branch already exists on origin and pass exit code to variable ot prevent script from stopping
        exitcode=0; git ls-remote --exit-code --heads origin UPSTREAM-$branch > /dev/null || exitcode=$?
        # if branch already exists in remote
        if [ "$exitcode" == "0" ]; then
          echo "checking out existing branch UPSTREAM-$branch"
          git fetch
          git checkout --track origin/UPSTREAM-$branch
        # if it not exists: probably if running the first time
        else
          echo "checking out new orphan branch UPSTREAM-$branch"
          git checkout --orphan UPSTREAM-$branch
          git rm -rf .
        fi
        git merge -X theirs upstream/$branch
        git push -u --follow-tags origin UPSTREAM-$branch
        git push --tags
        git checkout master
        echo "... done"
      done
    # - cd ..
    # - rm -rf git_tmp
  only:
    - master
