[gem-rtsw-epics-base-testing]
releaser = tito.release.YumRepoReleaser
srpm_disttag = .el8
builder = tito.builder.MockBuilder
builder.mock = /etc/mock/gem-rtsw-epics-base-testing.cfg
builder.test = 1
rsync = hbfswgrepo-lv1.hi.gemini.edu:/rtsw/packages/gem-rtsw-testing/epics-base/centos-8/x86_64/

[gem-rtsw-epics-base-stable]
releaser = tito.release.YumRepoReleaser
srpm_disttag = .el8
builder = tito.builder.MockBuilder
builder.mock = /etc/mock/gem-rtsw-epics-base-stable.cfg
builder.test = 1
rsync = hbfswgrepo-lv1.hi.gemini.edu:/rtsw/packages/gem-rtsw-stable/epics-base/centos-8/x86_64/

[gem-rtsw-epics-base-unstable]
releaser = tito.release.YumRepoReleaser
srpm_disttag = .el8
builder = tito.builder.MockBuilder
builder.mock = /etc/mock/gem-rtsw-epics-base-unstable.cfg
builder.test = 1
rsync = hbfswgrepo-lv1.hi.gemini.edu:/rtsw/packages/gem-rtsw-unstable/epics-base/<BRANCH>/centos-8/x86_64/

