
common_create-rpm-env:
    extends:
        .create-rpm-env

common_create-config:
    extends:
        .create-config

common_deploy-to-rpm-repo:
    extends:
        .deploy-to-rpm-repo

common_deploy-container:
    extends:
        .deploy-container

common_set-base-container:
    extends:
        .set-base-container

common_deploy-other-rpm:
    extends:
        .deploy-other-rpm

common_trigger-container-rebuild:
    extends:
        .trigger-container-rebuild

