FROM <BASE_CONTAINER>
ENV container docker
STOPSIGNAL SIGRTMIN+3

RUN dnf -y update

RUN dnf -y install glibc-langpack-en
RUN dnf -y install epel-release
RUN dnf -y install dnf-plugins-core
RUN dnf config-manager --set-enabled powertools

RUN dnf -y groupinstall "Development Tools"
RUN dnf -y install sssd-client
RUN dnf -y install sudo
RUN dnf -y install perl-interpreter
RUN dnf -y install openssh-clients
RUN dnf -y install yum-utils
RUN dnf -y install python3-gitlab
RUN alternatives --set python /usr/bin/python3

# disable kdump service as it is throwing an error on some hosts 
# (e.g. hbfade)
RUN systemctl disable kdump 

# copy repo information which is created
# by gitlab-ci in an earlier stage
COPY gem-rtsw-common.repo /etc/yum.repos.d/

# copy mock configuration which is created
# by gitlab-ci in an earlier stage
COPY gem-rtsw-common.cfg /etc/mock/
COPY gem-rtsw-common.tpl /etc/mock/templates/

# copy tito releaser.conf to global directory
# to be used with appropriate gemini-ade scripts
# for 'tito release' command
COPY releasers.conf /gem_base/usr/share/tito/common/

RUN dnf config-manager --enable gem-rtsw-common-<MATURITY>
RUN dnf makecache || echo "!! failed to make cache, is the repository initialized already? !!"

# install all available packages from common repo
RUN repoquery --disablerepo="*" --enablerepo="gem-rtsw-common*" --queryformat "%{NAME}\n" --available > packagelist.txt
RUN xargs dnf -y install < packagelist.txt || printf '!! failed to install package !! \n\
Is it deployed to the RPM repository already?'

RUN dnf clean all

CMD ["/sbin/init"]

