[gem-rtsw-common-testing]
releaser = tito.release.YumRepoReleaser
srpm_disttag = .el8
builder = tito.builder.MockBuilder
builder.mock = /etc/mock/gem-rtsw-common-testing.cfg
builder.test = 1
rsync = hbfswgrepo-lv1.hi.gemini.edu:/rtsw/packages/gem-rtsw-testing/common/<BRANCH>/centos-8/x86_64/

[gem-rtsw-common-stable]
releaser = tito.release.YumRepoReleaser
srpm_disttag = .el8
builder = tito.builder.MockBuilder
builder.mock = /etc/mock/gem-rtsw-common-stable.cfg
builder.test = 1
rsync = hbfswgrepo-lv1.hi.gemini.edu:/rtsw/packages/gem-rtsw-stable/common/<BRANCH>/centos-8/x86_64/

[gem-rtsw-common-unstable]
releaser = tito.release.YumRepoReleaser
srpm_disttag = .el8
builder = tito.builder.MockBuilder
builder.mock = /etc/mock/gem-rtsw-common-unstable.cfg
builder.test = 1
rsync = hbfswgrepo-lv1.hi.gemini.edu:/rtsw/packages/gem-rtsw-unstable/common/<BRANCH>/centos-8/x86_64/

